<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON4STJ" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

</Project>
