<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastAddress.Sdk\FastAddress.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FastAddress.Api.Tests" />
  </ItemGroup>

</Project>
